services:
  load-balance:
    container_name: load-balance-rs
    image: alexroza/ld-tr
    environment:
      - PAYMENT_PROCESSOR_DEFAULT=http://payment-processor-default:8080
      - PAYMENT_PROCESSOR_FALLBACK=http://payment-processor-fallback:8080
    networks:
      - backend
      - payment-processor
  app-one:
    image: alexroza/b-rs
    environment:
      - LOAD_BALANCE=http://load-balance-rs:8081
    networks:
      - backend
      - payment-processor
  app-two:
    image: alexroza/b-rs
    environment:
      - LOAD_BALANCE=http://load-balance-rs:8081
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true